import type { DeviceProfile } from "@/lib/types";

/**
 * The catalog of emulatable device + browser combos.
 * `{v}` in the UA string is replaced at launch time with the exact
 * version of the engine binary that Playwright downloaded, so the
 * User-Agent always matches the real engine underneath.
 */
export const PROFILES: DeviceProfile[] = [
  {
    id: "win-chrome",
    label: "Windows 11 · Chrome",
    os: "windows",
    osLabel: "Windows 11",
    browserName: "Chrome",
    engine: "chromium",
    kind: "desktop",
    width: 1440,
    height: 900,
    dpr: 1,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{v} Safari/537.36",
  },
  {
    id: "win-edge",
    label: "Windows 11 · Edge",
    os: "windows",
    osLabel: "Windows 11",
    browserName: "Edge",
    engine: "chromium",
    kind: "desktop",
    width: 1440,
    height: 900,
    dpr: 1,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{v} Safari/537.36 Edg/{v}",
  },
  {
    id: "win-firefox",
    label: "Windows 11 · Firefox",
    os: "windows",
    osLabel: "Windows 11",
    browserName: "Firefox",
    engine: "firefox",
    kind: "desktop",
    width: 1440,
    height: 900,
    dpr: 1,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:{v}) Gecko/20100101 Firefox/{v}",
  },
  {
    id: "mac-safari",
    label: "macOS Sequoia · Safari",
    os: "macos",
    osLabel: "macOS 15",
    browserName: "Safari",
    engine: "webkit",
    kind: "desktop",
    width: 1512,
    height: 945,
    dpr: 2,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.0 Safari/605.1.15",
  },
  {
    id: "mac-chrome",
    label: "macOS Sequoia · Chrome",
    os: "macos",
    osLabel: "macOS 15",
    browserName: "Chrome",
    engine: "chromium",
    kind: "desktop",
    width: 1512,
    height: 945,
    dpr: 2,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{v} Safari/537.36",
  },
  {
    id: "mac-firefox",
    label: "macOS Sequoia · Firefox",
    os: "macos",
    osLabel: "macOS 15",
    browserName: "Firefox",
    engine: "firefox",
    kind: "desktop",
    width: 1512,
    height: 945,
    dpr: 2,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:{v}) Gecko/20100101 Firefox/{v}",
  },
  {
    id: "linux-chrome",
    label: "Ubuntu Linux · Chrome",
    os: "linux",
    osLabel: "Ubuntu 24.04",
    browserName: "Chrome",
    engine: "chromium",
    kind: "desktop",
    width: 1366,
    height: 860,
    dpr: 1,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{v} Safari/537.36",
  },
  {
    id: "linux-firefox",
    label: "Ubuntu Linux · Firefox",
    os: "linux",
    osLabel: "Ubuntu 24.04",
    browserName: "Firefox",
    engine: "firefox",
    kind: "desktop",
    width: 1366,
    height: 860,
    dpr: 1,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (X11; Linux x86_64; rv:{v}) Gecko/20100101 Firefox/{v}",
  },
  {
    id: "android-chrome",
    label: "Pixel 9 Pro · Chrome",
    os: "android",
    osLabel: "Android 16",
    browserName: "Chrome",
    engine: "chromium",
    kind: "phone",
    width: 412,
    height: 915,
    dpr: 2.625,
    touch: true,
    mobile: true,
    ua: "Mozilla/5.0 (Linux; Android 16; Pixel 9 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{v} Mobile Safari/537.36",
  },
  {
    id: "android-firefox",
    label: "Pixel 9 · Firefox",
    os: "android",
    osLabel: "Android 16",
    browserName: "Firefox",
    engine: "firefox",
    kind: "phone",
    width: 412,
    height: 915,
    dpr: 2.625,
    touch: true,
    mobile: true,
    ua: "Mozilla/5.0 (Android 16; Mobile; rv:{v}) Gecko/{v} Firefox/{v}",
  },
  {
    id: "android-ddg",
    label: "Pixel 9 · DuckDuckGo",
    os: "android",
    osLabel: "Android 16",
    browserName: "DuckDuckGo",
    engine: "chromium",
    kind: "phone",
    width: 412,
    height: 915,
    dpr: 2.625,
    touch: true,
    mobile: true,
    ua: "Mozilla/5.0 (Linux; Android 16; Pixel 9) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/{v} Mobile Safari/537.36 DuckDuckGo/5",
    note: "Tracker blocking simulated via privacy-hardened context",
  },
  {
    id: "android-tablet",
    label: "Galaxy Tab S10 · Chrome",
    os: "android",
    osLabel: "Android 15",
    browserName: "Chrome",
    engine: "chromium",
    kind: "tablet",
    width: 800,
    height: 1280,
    dpr: 2,
    touch: true,
    mobile: true,
    ua: "Mozilla/5.0 (Linux; Android 15; SM-X826B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{v} Safari/537.36",
  },
  {
    id: "iphone-safari",
    label: "iPhone 16 Pro · Safari",
    os: "ios",
    osLabel: "iOS 26",
    browserName: "Safari",
    engine: "webkit",
    kind: "phone",
    width: 402,
    height: 874,
    dpr: 3,
    touch: true,
    mobile: true,
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 26_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.0 Mobile/15E148 Safari/604.1",
  },
  {
    id: "ipad-safari",
    label: "iPad Pro 11\u2033 · Safari",
    os: "ios",
    osLabel: "iPadOS 26",
    browserName: "Safari",
    engine: "webkit",
    kind: "tablet",
    width: 834,
    height: 1194,
    dpr: 2,
    touch: true,
    mobile: true,
    ua: "Mozilla/5.0 (iPad; CPU OS 26_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.0 Mobile/15E148 Safari/604.1",
  },
  {
    id: "tor",
    label: "Tor Browser · Real",
    os: "windows",
    osLabel: "Tor Network",
    browserName: "Tor Browser",
    engine: "chromium",
    kind: "privacy",
    width: 1000,
    height: 960,
    dpr: 1,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0",
    note: "Real Tor circuit via local daemon SOCKS5. All traffic routed through onion relays. Google search (only engine that accepts Tor exits).",
  },
  {
    id: "win-ddg",
    label: "Windows 11 · DuckDuckGo",
    os: "windows",
    osLabel: "Windows 11",
    browserName: "DuckDuckGo",
    engine: "chromium",
    kind: "privacy",
    width: 1440,
    height: 900,
    dpr: 1,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{v} Safari/537.36",
    note: "DuckDuckGo search by default. Privacy-hardened context.",
  },
  {
    id: "win-mullvad",
    label: "Windows 11 · Mullvad",
    os: "windows",
    osLabel: "Windows 11",
    browserName: "Mullvad Browser",
    engine: "firefox",
    kind: "privacy",
    width: 1400,
    height: 900,
    dpr: 1,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (Windows NT 10.0; rv:{v}) Gecko/20100101 Firefox/{v}",
    note: "Mullvad Browser: Firefox-based, anti-fingerprinting, Brave Search.",
  },
  {
    id: "win-brave",
    label: "Windows 11 · Brave",
    os: "windows",
    osLabel: "Windows 11",
    browserName: "Brave",
    engine: "chromium",
    kind: "privacy",
    width: 1440,
    height: 900,
    dpr: 1,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{v} Safari/537.36",
    note: "Brave Search by default. Anti-fingerprinting enabled.",
  },
  {
    id: "android-brave",
    label: "Pixel 9 · Brave",
    os: "android",
    osLabel: "Android 16",
    browserName: "Brave",
    engine: "chromium",
    kind: "phone",
    width: 412,
    height: 915,
    dpr: 2.625,
    touch: true,
    mobile: true,
    ua: "Mozilla/5.0 (Linux; Android 16; Pixel 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{v} Mobile Safari/537.36 Brave/{v}",
    note: "Brave Search by default.",
  },
  {
    id: "android-opera",
    label: "Pixel 9 · Opera",
    os: "android",
    osLabel: "Android 16",
    browserName: "Opera",
    engine: "chromium",
    kind: "phone",
    width: 412,
    height: 915,
    dpr: 2.625,
    touch: true,
    mobile: true,
    ua: "Mozilla/5.0 (Linux; Android 16; Pixel 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{v} Mobile Safari/537.36 OPR/{v}",
  },
  {
    id: "mac-opera",
    label: "macOS · Opera",
    os: "macos",
    osLabel: "macOS 15",
    browserName: "Opera",
    engine: "chromium",
    kind: "desktop",
    width: 1440,
    height: 900,
    dpr: 2,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{v} Safari/537.36 OPR/{v}",
  },
  {
    id: "linux-vivaldi",
    label: "Linux · Vivaldi",
    os: "linux",
    osLabel: "Ubuntu 24.04",
    browserName: "Vivaldi",
    engine: "chromium",
    kind: "desktop",
    width: 1440,
    height: 900,
    dpr: 1,
    touch: false,
    mobile: false,
    ua: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{v} Vivaldi/{v} Safari/537.36",
  },
  {
    id: "iphone-chrome",
    label: "iPhone 16 Pro · Chrome",
    os: "ios",
    osLabel: "iOS 18",
    browserName: "Chrome",
    engine: "chromium",
    kind: "phone",
    width: 402,
    height: 874,
    dpr: 3,
    touch: true,
    mobile: true,
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/{v} Mobile/15E148 Safari/604.1",
  },
  {
    id: "ipad-chrome",
    label: "iPad Pro 11\u2033 · Chrome",
    os: "ios",
    osLabel: "iPadOS 18",
    browserName: "Chrome",
    engine: "chromium",
    kind: "tablet",
    width: 834,
    height: 1194,
    dpr: 2,
    touch: true,
    mobile: true,
    ua: "Mozilla/5.0 (iPad; CPU OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/{v} Mobile/15E148 Safari/604.1",
  },
];

export function getProfile(id: string): DeviceProfile | undefined {
  return PROFILES.find((p) => p.id === id);
}
